namespace Arrowgene.DJMaxOnline.Server;

public enum PacketId : ushort
{
    // OnInitialize = 0x00, - Not a Packet
    // OnRegister = 0x00, - Not a Packet
    // Resume = 0x00, - Not a Packet
    // OnConnect = 0x00, - Not a Packet
    // ClearChannelInfo = 0x00, not a packet
    // InitReq = 0x00, 
    // Suspend = 0x00, 
    // OnDestroy = 0x00, 
    // OnDisconnect = 0x00, 
    // ClearWaiterInfo = 0x00,  
    // ClearJoinerInfo = 0x00,
    // ClearCourseList = 0x00, // not a packet
    // ClearUserIdInfo = 0x00,
    // ClearRoomInfo = 0x00, 
    //   EraseRoomInfo = 0x00, 
    //   EraseJoinerInfo = 0x00, 
    //   EraseWaiterInfo = 0x00,  
    //   UpdateWaiterInfo = 0x00, 
    //    AuthenticateInReq = 0x00,  // maybe only for korea and japanese client?
    //   UpdateRoomInfo = 0x00, // ?? 
    //   UpdateJoinerInfo = 0x00,// ??
    //   Report = 0x00, // what is this? sub_438FD0

    // Test00 = 0x1b, // delte for testing
    Test01 = 0xF0, // delte for testing
    Test02 = 0x51, // delte for testing 
    ConnectReq = 0x0A, //0x17
    OnConnectAck = 0x09, //0x2F
    AuthenticateInSndAccReq = 0x11, //0x43
    AuthenticateInSndeKeyAck = 0x13, //0x14u
    OnAuthenticateInAck = 0x10,  //0x5C
    OnAuthenticateInSndeKeyReq = 0x12, //0x8
    OnAuthenticateInSndrPwdReq = 0x14, //0x9u
    AuthenticateInSndrPwdAck = 0x15,  //0x14u
    OnUbsAccountAuthenResAck = 0x12D, // ?? 
    OnUbsAwardInfoInf = 0x12E, //0xA9u
    OnUbsAwardAuthenAck = 0x130, // ??
    KeepAuthenticateInReq = 0x17, //0xFu
    OnKeepAuthenticateInAck = 0x16, // ??
    LogInReq = 0x1B, //0x35u
    OnUserInfoInf = 0x43, //0x87u
    OnInventoryInfoInf = 0x44, //0x2ECu
    OnMessengerInfoInf = 0x45, //0x3B6u
    OnLogInAck = 0x1A, //??
    LogOutReq = 0x19, //0xDu
    OnLogOutAck = 0x18,//??
    OnChannelInfoInf = 0x0B, //0x5Au
    OnPeerCountInf = 0x0C, //0xAu
    OnDisconnectPeerInf = 0x08, //??
    AliveAck = 0x06, //3u
    OnAliveReq = 0x07, //3u
    OnPingTestInf = 0x03, //?
    PingTestInf = 0x04, //3u
    UserInfoReq = 0x1D, //0xFu
    OnUserInfoAck = 0x1F, //??
    OnUserInfoResNotFound = 0x1E, //??
    OnBigNewsInf = 0x97,//??
    OnChatInf = 0x39, // game sends 0x38.
    OnWChatInf = 0x37, //maybe same pattern?(0x36)
    OnCourseListInf = 0x82, //??
    OnCourseRankAck = 0x84, //??
    OnChangeCourseAck = 0x86, //??
    OnContinueCourseAck = 0x88, //??
    OnPostCourseItemReq = 0x89, //??
    OnAwardItemInf = 0x8C, //??
    OnCipherCommandInf = 0x10E, //admin command based on csv? is this even used? 
    OnEnvironmentInf = 0xFC, // ??
    OnSystemInfoAck = 0xFE, //??
    OnWaiterInfoUpdateInf = 0x3C, //??
    OnWaiterInfoEraseInf = 0x3D, //??
    OnRoomInfoUpdateInf = 0x3A, // 0x30u
    OnRoomInfoEraseInf = 0x3B, //?
    UserIdInfoReq = 0x21, // ?
    OnUserIdInfoAck = 0x22, //0x43u
    OnUserIdInfoInf = 0x20, //0x43u
    OnJoinerListStart = 0x40, //??
    OnJoinerListEnt = 0x41, //??
    OnJoinerListEnd = 0x42, //??
    CreateRoomReq = 0x4C, // ?? maybe 0x3Bu
    OnCreateRoomAck = 0x75, //?? 
    JoinRoomReq = 0x46, // 0x19u
    OnJoinRoomAck = 0x47, //0x30u
    OnPostJoinRoomInf = 0x48, //??
    InviteRejectReq = 0xA6,  //0xCu
    OnInviteRejectAck = 0xA7,//??
    OnRoomDescInf = 0x50, //??
    OnQuickInviteAck = 0xA1, //??
    OnInviteReq = 0xA2, //??
    QuickInviteReq = 0xA0, //0xB
    RoomChangeInfoReq = 0x9C, //  sub_436160 ?
    OnRoomChangeInfoAck = 0x9D,//??  0x21u???????
    TeamControlReq = 0x58, //0xCu
    OnTeamControlInf = 0x59, //??
    OnGameTypeInf = 0x5B,//??
    ReadyReq = 0x5D, //0xBu
    OnReadyInf = 0x5E, //??
    StartReq = 0x5F, //0xDu
    OnStartInf = 0x60, // ?? 0xFF, 0xE
    OnJoinEventInf = 0x61,//??
    OnEventInfoInf = 0x63, //??
    PlayStartReq = 0x64, //0xBu
    OnPlayStartInf = 0x65, //??
    PlaySkipReq = 0x67, //0xBu
    OnPlaySkipInf = 0x68,//??
    PlayOverReq = 0x6A, //0xBu
    OnPlayOverInf = 0x6B,//??
    PlayStateInf = 0x6C, //0x1Eu
    OnPlayStateInf = 0x6D,// ??
    OnCheckDataReq = 0x71, //??
    OnLoadCompleteInf = 0x7C, //??
    StageResultInf = 0x49, //0x3Bu
    OnStageResultExInf = 0x70,//??
    LeaveRoomReq = 0x73, // 0xBu
    OnLeaveRoomAck = 0x74, //??
    ChangeDiscReq = 0x76, //0x11u
    OnChangeDiscInf = 0x77,//??
    OnAwardInfoInf = 0x78, //????
    OnGameInfoInf = 0x7A, //???
    UpdateUserAccountNickReq = 0x30,  //0x1Cu
    OnUpdateUserAccountNickAck = 0x31, //??
    UpdateUserProfileReq = 0x32,  //0x12u
    OnUpdateUserProfileAck = 0x33, // ??
    OnUpdateUserIconInf = 0x24, //??
    OnUpdateUserPropertyInf = 0x25, //??
    OnUpdateUserPropertyRecordInf = 0x28, //??
    OnUpdateUserPropertyMiscInf = 0x29,//??
    OnUpdateUserPropertyLevelInf = 0x26, //??
    OnUpdateUserPropertyMoneyInf = 0x27, //??
    OnUpdateUserInventoryDefaultItemInf = 0x2A, //0xC0u
    OnUpdateUserInventoryEventItemInf = 0x2B, //0x80u
    OnUpdateUserInventoryShopItemInf = 0x2C, //0xF0u
    OnUpdateUserInventoryMountItemInf = 0x2D, //0x40u
    OnUpdateUserInventoryPresentItemInf = 0x2E, //0x78u
    GetItemReq = 0xB4, //0xBu
    OnCrItemInf = 0xB3, //??
    OnGetItemFail = 0xB5, //??
    OnGetItemAck = 0xB6, //??
    ItemLevelUpReq = 0xB7,  // 0xBu
    OnItemLevelUpFail = 0xB8, //??
    OnItemLevelUpAck = 0xB9, //??
    UseItemReq = 0xBA, //0xCu
    OnUseItemFail = 0xBB,//??
    OnUseItemAck = 0xBC,//??
    OnGoodLuckInf = 0xBD, //?? 
    OnGoodLuckListInf = 0xBE, //??
    OnMissionStandItemInf = 0xC0, //??
    UseEffectorInf = 0xC3,  //??
    UseEffectorSetInf = 0xC6, //0x13u
    OnUseEffectorInf = 0xC4, //??
    OnUseEffectorSetInf = 0xC6, //??
    UseMountItemInf = 0xC8, //0x40u
    OnUseMountItemInf = 0xC9, //0x40u
    OnStartParameterInf = 0xCA, //??
    OnBillingAuthInf = 0xD2, //??
    OnGameStartInf = 0xD3, //??
    OnUserAlertInf = 0xD4, //??
    MountItemReq = 0xD7, //0x43u
    OnMountItemAck = 0xD8, //0x40u
    GetPresentItemReq = 0xD9, //0xFu
    OnGetPresentItemAck = 0xDA, //?? sub_439740 two values
    DeleteItemReq = 0xDB, //0x13u
    OnDeleteItemAck = 0xDC,//0xF0u
    OnExpiredMountItemInf = 0xE4, //0xF0u
    OnExpiredShopItemInf = 0xE5, //0xF0u
    OnAlertCreditInf = 0xE6,//??
    OnMsgNotifyInf = 0xF1,//??
    MsgRegisterUserReq = 0xF2, //0x24u
    OnMsgRegisterUserAck = 0xF3, //??
    OnMsgRegUserInf = 0xF4, //??
    OnMsgBlkUserInf = 0xF5, // 0xF0u
    OnMsgGroupInf = 0xF6, //0xE6u
    PurchaseItemReq = 0xDD,  //0x23u
    OnPurchaseItemAck = 0xDE, //F0
    ResaleItemReq = 0xDF, //  0x13u
    OnResaleItemAck = 0xE0, //0xF0u
    OnUpdateUserAccountClassInf = 0x2F, //??
    VerifyCodeInf = 0xE7, //0x23u
}
