namespace Arrowgene.DJMaxOnline.Server;

public enum PacketId : ushort
{
    // OnInitialize = 0x00, - Not a Packet
    // OnRegister = 0x00, - Not a Packet
    // Resume = 0x00, - Not a Packet
    // OnConnect = 0x00, - Not a Packet
    // ClearChannelInfo = 0x00, not a packet
    // InitReq = 0x00, not a packet
    // Suspend = 0x00, not a packet
    // OnDestroy = 0x00, not a packet
    // OnDisconnect = 0x00, not a packet
    // ClearWaiterInfo = 0x00,  not a packet
    // ClearJoinerInfo = 0x00,not a packet
    // ClearCourseList = 0x00, not a packet
    // ClearUserIdInfo = 0x00,not a packet
    // ClearRoomInfo = 0x00, not a packet
    //EraseRoomInfo = 0x00, not a packet
    //EraseJoinerInfo = 0x00, not a packet
    //EraseWaiterInfo = 0x00, not a packet
    //UpdateWaiterInfo = 0x00, not a packet
    //AuthenticateInReq = 0x00,  // maybe only for korea and japanese client?
    //UpdateRoomInfo = 0x00, not a packet
    //Report = 0x00, // what is this? sub_438FD0

    // Test00 = 0x1b, // delte for testing
    sub_439B30 = 0xF0, // delte for testing
    sub_434390 = 0x83, //0xD
    sub_434450 = 0x85, //0xD
    sub_434510 = 0x87, //0xD
    sub_434620 = 0x8A, //0xB
    sub_434B40 = 0xFD, //0xD
    sub_435F20 = 0x53, //0xC
    sub_436120 = 0xA3, //0xB
    sub_4362D0 = 0x56, //0xC
    sub_437370 = 0x72, //0x103
    sub_437900 = 0x23, //0xF
    sub_432210 = 0x12C, //0xB
    sub_4323D0 = 0x12F, //0x26
    OnUpdateJoinerInfoInf = 0x51, // name sake for sub_4365B0
    ConnectReq = 0x0A, //0x17
    OnConnectAck = 0x09, //0x2F
    AuthenticateInSndAccReq = 0x11, 
    AuthenticateInSndeKeyAck = 0x13, 
    OnAuthenticateInAck = 0x10,  
    OnAuthenticateInSndeKeyReq = 0x12, //0x8
    OnAuthenticateInSndrPwdReq = 0x14, //0x9
    AuthenticateInSndrPwdAck = 0x15,  //0x14
    OnUbsAccountAuthenResAck = 0x12D, // ?? 
    OnUbsAwardInfoInf = 0x12E, //176
    OnUbsAwardAuthenAck = 0x130, // ??
    KeepAuthenticateInReq = 0x17, 
    OnKeepAuthenticateInAck = 0x16, 
    LogInReq = 0x1B, 
    OnUserInfoInf = 0x43, 
    OnInventoryInfoInf = 0x44, 
    OnMessengerInfoInf = 0x45, 
    OnLogInAck = 0x1A,
    LogOutReq = 0x19, //0xDu
    OnLogOutAck = 0x18,
    OnChannelInfoInf = 0x0B, 
    OnPeerCountInf = 0x0C, 
    OnDisconnectPeerInf = 0x08, //??
    AliveAck = 0x06, 
    OnAliveReq = 0x07, 
    OnPingTestInf = 0x03, 
    PingTestInf = 0x04, 
    UserInfoReq = 0x1D, 
    OnUserInfoAck = 0x1F, //??
    OnUserInfoResNotFound = 0x1E, //??
    OnBigNewsInf = 0x97,//??
    OnChatInf = 0x39, // game sends 0x38.
    OnWChatInf = 0x37, //maybe same pattern?(0x36)
    OnCourseListInf = 0x82, //??
    OnCourseRankAck = 0x84, //??
    OnChangeCourseAck = 0x86, //??
    OnContinueCourseAck = 0x88, //??
    OnPostCourseItemReq = 0x89, //??
    OnAwardItemInf = 0x8C, //??
    OnCipherCommandInf = 0x10E, //admin command based on csv? is this even used? 
    OnEnvironmentInf = 0xFC, 
    OnSystemInfoAck = 0xFE, //??
    OnWaiterInfoUpdateInf = 0x3C, 
    OnWaiterInfoEraseInf = 0x3D, //??
    OnRoomInfoUpdateInf = 0x3A, 
    OnRoomInfoEraseInf = 0x3B, 
    UserIdInfoReq = 0x21, // ??
    OnUserIdInfoAck = 0x22, 
    OnUserIdInfoInf = 0x20, 
    OnJoinerListStart = 0x40, //??   
    OnJoinerListEnt = 0x41, //??  
    OnJoinerListEnd = 0x42, //??
    CreateRoomReq = 0x4C, 
    OnCreateRoomAck = 0x4D, 
    JoinRoomReq = 0x46, 
    OnJoinRoomAck = 0x47, 
    OnPostJoinRoomInf = 0x48,
    InviteRejectReq = 0xA6, 
    OnInviteRejectAck = 0xA7,
    OnRoomDescInf = 0x50, 
    OnQuickInviteAck = 0xA1, //??
    OnInviteReq = 0xA2, 
    QuickInviteReq = 0xA0, 
    RoomChangeInfoReq = 0x9C, 
    OnRoomChangeInfoAck = 0x9D,
    TeamControlReq = 0x58, 
    OnTeamControlInf = 0x59, //??
    OnGameTypeInf = 0x5B,//??
    ReadyReq = 0x5D,
    OnReadyInf = 0x5E,
    StartReq = 0x5F,
    OnStartInf = 0x60,
    OnJoinEventInf = 0x61,
    OnEventInfoInf = 0x63, //??
    PlayStartReq = 0x64, 
    OnPlayStartInf = 0x65, 
    PlaySkipReq = 0x67, 
    OnPlaySkipInf = 0x68,//??
    PlayOverReq = 0x6A,
    OnPlayOverInf = 0x6B,
    PlayStateInf = 0x6C, 
    OnPlayStateInf = 0x6D,// ??
    OnCheckDataReq = 0x71, 
    OnLoadCompleteInf = 0x7C, //??
    StageResultInf = 0x49, 
    OnStageResultExInf = 0x70,
    LeaveRoomReq = 0x73, 
    OnLeaveRoomAck = 0x74, 
    ChangeDiscReq = 0x76, 
    OnChangeDiscInf = 0x77,//??
    OnAwardInfoInf = 0x78, //????
    OnGameInfoInf = 0x7A, 
    UpdateUserAccountNickReq = 0x30,  
    OnUpdateUserAccountNickAck = 0x31, //??
    UpdateUserProfileReq = 0x32,  
    OnUpdateUserProfileAck = 0x33, // ??
    OnUpdateUserIconInf = 0x24, //??
    OnUpdateUserPropertyInf = 0x25, 
    OnUpdateUserPropertyRecordInf = 0x28, //??
    OnUpdateUserPropertyMiscInf = 0x29,//??
    OnUpdateUserPropertyLevelInf = 0x26, //??
    OnUpdateUserPropertyMoneyInf = 0x27, //??
    OnUpdateUserInventoryDefaultItemInf = 0x2A, 
    OnUpdateUserInventoryEventItemInf = 0x2B, 
    OnUpdateUserInventoryShopItemInf = 0x2C, 
    OnUpdateUserInventoryMountItemInf = 0x2D, 
    OnUpdateUserInventoryPresentItemInf = 0x2E, 
    GetItemReq = 0xB4, 
    OnCrItemInf = 0xB3, //??
    OnGetItemFail = 0xB5, //??
    OnGetItemAck = 0xB6, //??
    ItemLevelUpReq = 0xB7,  
    OnItemLevelUpFail = 0xB8, //??
    OnItemLevelUpAck = 0xB9, //??
    UseItemReq = 0xBA, 
    OnUseItemFail = 0xBB,//??
    OnUseItemAck = 0xBC,//??
    OnGoodLuckInf = 0xBD, //?? 
    OnGoodLuckListInf = 0xBE, //??
    OnMissionStandItemInf = 0xC0, //??
    UseEffectorInf = 0xC3,  
    UseEffectorSetInf = 0xC5, 
    OnUseEffectorInf = 0xC4, 
    OnUseEffectorSetInf = 0xC6, //??
    UseMountItemInf = 0xC8, 
    OnUseMountItemInf = 0xC9, 
    OnStartParameterInf = 0xCA, 
    OnBillingAuthInf = 0xD2, //??
    OnGameStartInf = 0xD3, 
    OnUserAlertInf = 0xD4, //??
    MountItemReq = 0xD7, 
    OnMountItemAck = 0xD8, 
    GetPresentItemReq = 0xD9, 
    OnGetPresentItemAck = 0xDA, 
    DeleteItemReq = 0xDB, 
    OnDeleteItemAck = 0xDC,
    OnExpiredMountItemInf = 0xE4, 
    OnExpiredShopItemInf = 0xE5, 
    OnAlertCreditInf = 0xE6,//??
    OnMsgNotifyInf = 0xF1,//??
    MsgRegisterUserReq = 0xF2, 
    OnMsgRegisterUserAck = 0xF3, //??
    OnMsgRegUserInf = 0xF4, 
    OnMsgBlkUserInf = 0xF5, 
    OnMsgGroupInf = 0xF6, 
    PurchaseItemReq = 0xDD,  
    OnPurchaseItemAck = 0xDE, 
    ResaleItemReq = 0xDF, 
    OnResaleItemAck = 0xE0, 
    OnUpdateUserAccountClassInf = 0x2F, 
    VerifyCodeInf = 0xE7, 
}
